### ISSUE TITLE
Protect from "Cannot open clipboard: Access denied"

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#330]
Currently BCEditor just lets those errors surface, and it looks bad. They seem to surface with greater frequency than when using SynEdit (almost never had that report with SynEdit).

The Windows clipboard has a system-wide lock, so Clipboard.Open can fail. Solutions are to either go low-level, or use a loop and try to attempt several times before firing the error.

For more details
http://stackoverflow.com/questions/1859102/how-can-i-fix-cannot-open-clipboard-access-denied-errors

**Comment by EricGrange** [comment]
Also see Issue #331

I suspect the issue is surfacing because the methods open/close the clipboard several times, if another application is watching the clipboard for changes, there is a high risk it will check in between those locks, which would trigger the access denied.

**Comment by bonecode** [comment]
Yep, that code is more or less from my old SynEdit fork. I checked my other closed-source control where I have done this slightly different way. Looks more like that second solution... maybe I use that.

**Comment by bonecode** [comment]
I fixed this a little bit but can you repeat your problem somehow?

**Comment by EricGrange** [comment]
Yes, still happens very easily. :/

With the improved monkey from #335, use just "ecCopy, ecCut, ecPaste" as workload and comment out the HardOpen/HardClose implementations, it fails very quickly.

**Comment by EricGrange** [comment]
Note that the frequency of the issue depends on other apps, if you have almost nothing opened in windows, it is rare, if you have a whole bunch of apps, all watching the clipboard to adjust their toolbar icons or whatever, it happens very often.

**Comment by bonecode** [comment]
No, it does not fail. What Windows version you're using?

**Comment by EricGrange** [comment]
Windows 2008, but with a whole bunch of stuff open (Delphi, notepad++, Excel 2011, a couple mstsc/RDP sessions, Chrome, a couple apps with BCEditor in them...)

**Comment by EricGrange** [comment]
I suspect the RDP sessions might be the worse of the bunch: they have clipboard mirroring active, so they continually watch the clipboard to replicate it both ways.

**Comment by bonecode** [comment]
That Windows 2008 must be the cause because with Windows 10 or 7 there isn't such a problem. I use my editor everyday and I have many applications open. I just opened the office applications and no problem at all.

**Comment by EricGrange** [comment]
Possibly, that said DoPasteFromClipboard should lock the clipboard just once, at the start, or it's possible the clipboard will no longer have the format when it's finally open.

A similar issue affects cut & copy: they lock/unlock multiple times, but the clipboard can have changed in between the locks, so they should lock just once, and release the lock only before exiting

(Clipboard supports nested locks just fine, so there is no harm to performing the OpenClipboard at the beginning of those methods)


```
  if not CanPaste then
    Exit;

  LTextCaretPosition := TextCaretPosition;
  LPasteMode := FSelection.Mode;

  if Clipboard.HasFormat(GClipboardFormatBCEditor) then
  begin
    if not OpenClipboard then
      Exit;
```

**Comment by bonecode** [comment]
DoPasteFromClipboard is locking the clipboard just once. It is getting the handle (Clipboard.GetAsHandle) to the stored items and locks it (GlobalLock), and unlocks it (GlobalUnlock).

**Comment by EricGrange** [comment]
The GlobalLock are not clipboard locks: they are nested inside clipboard locks.

Annotated a few of the locks: 

```
begin
  if not CanPaste then   // two implicit lock/unlock
    Exit;
...
  if Clipboard.HasFormat(GClipboardFormatBCEditor) then // one implicit lock
  begin
    if not OpenClipboard then /// explicit lock
      Exit;
...
  if Clipboard.HasFormat(GClipboardFormatBorland) then  // one implicit lock
  begin
    if not OpenClipboard then // explicit lock
      Exit;
... etc
```

**Comment by bonecode** [comment]
I am not getting this... for example:

```
function TClipboard.HasFormat(Format: Word): Boolean;

  function HasAPicture: Boolean;
  var
    Format: Word;
  begin
    Open;
    try
      Result := False;
      Format := EnumClipboardFormats(0);
      while Format <> 0 do
        if TPicture.SupportsClipboardFormat(Format) then
        begin
          Result := True;
          Break;
        end
        else Format := EnumClipboardFormats(Format);
    finally
      Close;
    end;
  end;

begin
  Result := IsClipboardFormatAvailable(Format) or ((Format = CF_PICTURE) and HasAPicture);
end;
``` 
IsClipboardFormatAvailable - Determines whether the clipboard contains data in the specified format.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms649047(v=vs.85).aspx

And that is creating a lock in some level?

**Comment by EricGrange** [comment]
The windows clipboard is under a system-wide lock system, IsClipboardFormatAvailable internally does a lock, checks the value, then unlock (except it does it in a way that cannot fail).

After that has been done, the clipboard can be changed, so the outcome is transient, meant for UI or quick checks. For actions, you should lock the clipboard, then check if the format is there. Calling IsClipboardFormatAvailable before locking does not ensure the format will still be there when the subsequent open is performed.

The result of "LGlobalMem := Clipboard.GetAsHandle(GClipboardFormatBCEditor);" should be checked, the previous "if Clipboard.HasFormat(GClipboardFormatBCEditor)" is performed before the open, so it does not ensure the format will still be there.

**Comment by bonecode** [comment]
I moved format checks inside clipboard open..close.
