### ISSUE TITLE
ecMove failure (yes, monkey is merciless)

### ISSUE THREAD

**Issue by EricGrange** [bonecode/TBCEditor#355]
RandSeed = 311

```
const
   cCommands : array [0..50] of Integer = (
      ecChar, ecString, ecChar, ecString, ecChar, ecString,
      ecTab, ecShiftTab,
      ecInsertLine, ecLineBreak,
      ecDeleteChar, ecBackspace, ecDeleteLine, ecDeleteWord,
      ecLeft, ecRight, ecUp, ecDown, ecPageUp, ecPageDown,
      ecSelectionLeft, ecSelectionRight, ecSelectionUp, ecSelectionDown,
      ecLineStart, ecLineEnd, ecWordLeft, ecWordRight,
      ecSelectionLineStart, ecSelectionLineEnd, ecSelectionWordLeft, ecSelectionWordRight,
      ecPageUp, ecPageDown,
      ecSelectionPageUp, ecSelectionPageDown,
      ecInsertMode, ecOverwriteMode,
      ecLineComment, ecBlockComment,
      ecBlockIndent, ecBlockUnindent,
      ecCopy, ecCut, ecPaste,
      ecUndo, ecRedo,
      ecMoveLineUp, ecMoveLineDown, ecMoveCharLeft, ecMoveCharRight
      );
   cNBActions = 10;
```

**Comment by bonecode** [comment]
Fixed, but next fail RandSeed = 429... have a break, take a banana.

**Comment by bonecode** [comment]
Fixed. I like it when removing code fixes the problem. :)

**Comment by EricGrange** [comment]
Still fails for RandSeed = 11405, ecString, ecSelectionUp, ecCopy, ecTab, ecMoveLineUp, ecDeleteWord, ecBlockIndent, ecMoveCharLeft

Maybe still got more code to remove :)

**Comment by bonecode** [comment]
No problem after tabulator was fixed.

**Comment by EricGrange** [comment]
11405 bug still here, was everything committed on your end?

**Comment by bonecode** [comment]
Yep, everything is committed.

**Comment by bonecode** [comment]
I take it back, Failed for RandSeed = 94.

**Comment by bonecode** [comment]
Fixed.
