### ISSUE TITLE
Incorrect scrollbar position after resize

### ISSUE THREAD

**Issue by GooD-NTS** [bonecode/TBCEditor#535]
After editor resize scroll position is not returns to normal.
This gif is explains everything:
![editorscrollbug](https://cloud.githubusercontent.com/assets/18674940/21963342/331169da-db4a-11e6-8100-bfc918efebad.gif)

**Comment by bonecode** [comment]
Fixed.

**Comment by GooD-NTS** [comment]
I believe this issue is still reproducible in the latest Demo (The latest update: 17.01.2017 22:17, UTC+02:00)

**Comment by bonecode** [comment]
No, it isn't.
